=== Default Binding Functionality

Argument binding is achieved through an api:mqtt.bind.MqttBinderRegistry[]. The registry is responsible for choosing which ann:mqtt.bind.MqttBinder[] should be responsible for binding an argument. There are two methods, `bindFrom` and `bindTo`, that control binding to subscribers and publishers respectively.

The registry supports argument binders that are used based on an annotation applied to the argument or the argument type. All argument binders must implement either api:mqtt.bind.AnnotatedMqttBinder[] or api:mqtt.bind.TypedMqttBinder[]. The exception to that rule is the api:mqtt.bind.FallbackMqttBinder[] which is used when no other binders support a given argument. The binder registry follows a small sequence of steps to attempt to find a binder that supports the argument.

. Search the annotation based binders for one that matches any annotation on the argument that is annotated with link:{apimicronaut}core/bind/annotation/Bindable.html[@Bindable].
. Search the type based binders for one that matches or is a subclass of the argument type.
. Return the default binder.

The default binder checks if the argument name matches one of the supported properties. If the name does not match, the body of the message is bound to the argument.

The api:mqtt.bind.MqttBindingContext[] is the context used to binding data from and to messages. Each implementation (v3 and v5) has their own implementation. If you know your binder will only be working with a specific implementation, binders can reference the implementation instead of the interface.

=== Custom Binding

To inject your own argument binding behavior, it is as simple as registering a bean. The existing binder registry will inject it and include it in the normal processing.

==== Annotation Binding

A custom annotation can be created to bind subscriber arguments. A custom binder can then be created to use that annotation. In this example an annotation is used to bind to the correlation data (only available in v5).

snippet::io.micronaut.mqtt.docs.custom.annotation.Correlation[tags="imports,clazz"]

<1> The link:{apimicronaut}core/bind/annotation/Bindable.html[@Bindable] annotation is required for the annotation to be considered for binding.

snippet::io.micronaut.mqtt.docs.custom.annotation.CorrelationAnnotationBinder[tags="imports,clazz"]

<1> The class is made a bean by annotating with `@Singleton`.
<2> The custom annotation is used as the generic type for the interface.
<3> The conversion service is injected into the instance.
<4> The correlation data is set from the publisher method value.
<5> The correlation data is returned to be bound to a subscriber method value.

The annotation can now be used on the argument in a subscriber method.

snippet::io.micronaut.mqtt.docs.custom.annotation.ProductListener[tags="imports,clazz"]

And in a publisher method.

snippet::io.micronaut.mqtt.docs.custom.annotation.ProductClient[tags="imports,clazz"]

==== Type Binding

A custom binder can be created to support any argument type. For example the following class could be created to bind values from user properties (V5 only). This functionality could allow the work of retrieving and converting the properties to occur in a single place instead of multiple times in your code.

snippet::io.micronaut.mqtt.docs.custom.type.ProductInfo[tags="clazz"]

<1> The `size` argument is not required
<2> The `count` argument is required
<3> The `sealed` argument is required

A type argument binder can then be created to create the `ProductInfo` instance to bind to and from method arguments.

snippet::io.micronaut.mqtt.docs.custom.type.ProductInfoTypeBinder[tags="imports,clazz"]

<1> The class is made a bean by annotating with `@Singleton`.
<2> The custom type is used as the generic type for the interface.
<3> The conversion service is injected into the instance.
<4> The properties are populated into user properties when publishing
<5> The properties are read and converted into a `ProductInfo` to be bound to a subscriber argument
