To add support for MQTT to an existing project, you must first add a dependency to your build depending on the version of MQTT you require:

dependency:micronaut-mqttv3[groupId="io.micronaut.mqtt"]

dependency:micronaut-mqttv5[groupId="io.micronaut.mqtt"]

== Creating an MQTT Publisher with @MqttPublisher

To create an MQTT client that produces messages you can simply define an interface that is annotated with `MqttPublisher`.

For example the following is a trivial `MqttPublisher` interface:

snippet::io.micronaut.mqtt.docs.quickstart.ProductClient[tags="imports,clazz", project-base="docs-examples/example]

<1> The `MqttPublisher` annotation is used to designate this interface as a client.
<2> The ann:mqtt.annotation.Topic[] annotation indicates which topic the message should be published to.
<3> The `send` method accepts single parameter which is the payload of the message.


At compile time Micronaut will produce an implementation of the above interface. You can retrieve an instance of `ProductClient` either by looking up the bean from the link:{apimicronaut}context/ApplicationContext.html[ApplicationContext] or by injecting the bean with `@Inject`:

snippet::io.micronaut.mqtt.docs.quickstart.QuickstartSpec[tags="producer"] project-base="docs-examples/example]

NOTE: Because the `send` method returns `void` this means the method will publish the message and block until the broker acknowledges the message.

== Creating an MQTT Subscriber with @MqttSubscriber

To listen to MQTT messages you can use the ann:mqtt.annotation.MqttSubscriber[] annotation to define a message listener.

The following example will listen for messages published by the `ProductClient` in the previous section:

snippet::io.micronaut.mqtt.docs.quickstart.ProductListener[tags="imports,clazz"] project-base="docs-examples/example]


<1> The ann:mqtt.annotation.MqttSubscriber[] is used to designate the bean as a message listener.
<2> The ann:mqtt.annotation.Topic[] annotation is used to indicate which topic to subscribe to.
<3> The `receive` method accepts a single parameter which is the payload of the message.
