plugins {
    id("org.graalvm.buildtools.native")
    id("io.micronaut.library")
}

repositories {
    mavenCentral()
}

configurations.all {
    resolutionStrategy.preferProjectModules()
}

dependencies {
    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mn.micronaut.http)
    testImplementation(mn.micronaut.json.core)
    testImplementation(mn.micronaut.http.client)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mnTest.micronaut.test.junit5)
    testImplementation(libs.awaitility)
    testImplementation(mnSerde.micronaut.serde.jackson)
    testRuntimeOnly(mnLogging.logback.classic)
    testRuntimeOnly(mnTest.junit.platform.launcher)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
}

micronaut {
    importMicronautPlatform = false
}

test {
    useJUnitPlatform()
}

graalvmNative {
    toolchainDetection.set(false)
}
