=== Publishers

It is also supported to supply properties when publishing messages. Any of the org.eclipse.paho.mqttv5.common.packet.MqttProperties can be set dynamically per execution or statically for all executions. Properties can be set using the ann:mqtt.v5.annotation.MqttProperty[] annotation.

snippet::io.micronaut.mqtt.docs.properties.ProductClient[tags="imports,clazz", project-base="docs-examples/example]

<1> Properties can be defined at the class level and will apply to all methods. If a property is defined on the method with the same name as one on the class, both values will be added.
<2> Multiple annotations can be used to set multiple properties on the method or class level.
<3> Properties can be set per execution. The name is inferred from the argument if the annotation value is not set. Parameter values override any property value set from method or class level annotations.

For method arguments, if the value is not supplied to the annotation, the argument name will be used as the property name. For example, `@MqttProperty String userId` would result in the property `userId` being set on the properties object before publishing.

IMPORTANT: If the annotation or argument name cannot be matched to a property name in the `MqttProperties` class, a user property will be added instead.

=== Subscribers

Any properties found in messages received can be bound to subscriber arguments through the ann:mqtt.v5.annotation.MqttProperty[] annotation.

snippet::io.micronaut.mqtt.docs.properties.ProductListener[tags="imports,clazz", project-base="docs-examples/example]

<1> The property will be bound from the user property `userId`.
<2> The property will be bound from the content type property and does not require the property to be present.
<3> The property will be bound from the user property `appId`.

NOTE: Arguments are required by default and an exception will be thrown if they cannot be found or converted to the requested type. Making the argument nullable allows null values to be accepted.
