plugins {
    id 'java-library'
    id 'groovy'
    id("io.micronaut.build.internal.mqtt-tests")
}

dependencies {
    testAnnotationProcessor(mn.micronaut.inject.java)
    testAnnotationProcessor(mnValidation.micronaut.validation.processor)
    testImplementation(mn.micronaut.http.validation)

    testImplementation(mnTest.junit.jupiter.api)
    testImplementation(mnTest.micronaut.test.junit5)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
    testImplementation projects.testSuiteUtils
    testImplementation projects.micronautMqttv5
    testImplementation(platform(mnTest.boms.testcontainers))
    testImplementation(libs.testcontainers)
    testImplementation(mnSerde.micronaut.serde.jackson)
    testRuntimeOnly(mnTest.junit.platform.launcher)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
}

tasks.named('test') {
    useJUnitPlatform()
}
