[versions]
micronaut = "5.0.0-M25"
micronaut-gradle-plugin = "4.6.2"
managed-mqttv3 = "1.2.5"
managed-mqttv5 = "1.2.5"
managed-hivemq-client = "1.3.13"

awaitility = "4.3.0"
bcpkix-jdk15on = "1.70"

micronaut-reactor = "4.0.0-M2"
micronaut-serde = "3.0.0-M8"

micronaut-validation = "5.0.0-M2"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor-bom", version.ref = "micronaut-reactor" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

managed-paho-mqttv3-client = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "managed-mqttv3" }
managed-paho-mqttv5-client = { module = "org.eclipse.paho:org.eclipse.paho.mqttv5.client", version.ref = "managed-mqttv5" }
managed-hivemq-client = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "managed-hivemq-client" }

awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
bcpkix-jdk15on = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bcpkix-jdk15on" }
testcontainers = { module = "org.testcontainers:testcontainers" }
testcontainers-hivemq = { module = "org.testcontainers:testcontainers-hivemq" }

micronaut-gradle-plugin = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref="micronaut-gradle-plugin" }
