plugins {
    id("io.micronaut.build.internal.mqtt-module")
}

dependencies {
    implementation(mn.micronaut.http)
    api projects.micronautMqttCore
    implementation(libs.bcpkix.jdk15on)
    testImplementation(platform(mnTest.boms.testcontainers))
    testImplementation projects.micronautMqttv5
}
