plugins {
    id("io.micronaut.build.internal.kotlin-kapt")
    id("io.micronaut.build.internal.mqtt-tests")
}

dependencies {
    runtimeOnly mnLogging.logback.classic
    api(mn.micronaut.inject)
    testAnnotationProcessor(mn.micronaut.inject.java)
    testAnnotationProcessor(mnValidation.micronaut.validation.processor)
    testImplementation(mnValidation.micronaut.validation)
    testImplementation(mnTest.micronaut.test.junit5)
    testImplementation(mnTest.junit.jupiter.api)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
    testRuntimeOnly(mnTest.junit.platform.launcher)
    kaptTest(mn.micronaut.inject.java)
    testImplementation(platform(mnTest.boms.testcontainers))
    testImplementation(libs.testcontainers)
    testImplementation projects.testSuiteUtils
    testImplementation projects.micronautMqttv5
    testImplementation(mnSerde.micronaut.serde.jackson)
}

tasks.named('test') {
    useJUnitPlatform()
}
